CREATE SCHEMA STARWARS;
USE STARWARS;

CREATE TABLE PLANET(
    ID INTEGER NOT NULL AUTO_INCREMENT  PRIMARY KEY
    NAME    VARCHAR(30) NOT NULL,
    TERRAIN VARCHAR(30) NOT NULL,
    CLIMATE   VARCHAR(30) NOT NULL, 
    TIMES_IN_MOVIE SMALLINT

);