CREATE SEQUENCE planet_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE planet(
    ID int generated by default as identity (start with 1) primary key,
    NAME    VARCHAR(30) NOT NULL,
    TERRAIN VARCHAR(30) NOT NULL,
    CLIMATE   VARCHAR(30) NOT NULL, 
    TIMES_IN_MOVIE SMALLINT NOT NULL
);